import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-small-parcel-guaranteed-service-refund-recovery",
  "engine": "recovery",
  "title": "Small Parcel Guaranteed Service Refund Recovery",
  "shortTitle": "Small Parcel Guaranteed Service Refund Recovery",
  "tagline": "Recover carrier service-guarantee refunds from late or failed parcel deliveries with contract and exception evidence.",
  "industry": "Parcel Spend Recovery",
  "buyer": "High-volume parcel shippers",
  "uiPort": 4696,
  "apiPort": 5696,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Small Parcel Guaranteed Service Refund Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits in one accountable workflow. Recover carrier service-guarantee refunds from late or failed parcel deliveries with contract and exception evidence.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Small Parcel Guaranteed Service Refund Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("carrier-agreement-library","SPG01","Carrier agreement library","Execute carrier agreement library using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed carrier agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Carrier agreement library Reference","text","SPG01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("package-manifest-ingestion","SPG02","Package manifest ingestion","Execute package manifest ingestion using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed package manifest ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Package manifest ingestion Reference","text","SPG02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("tracking-event-timeline","SPG03","Tracking event timeline","Execute tracking event timeline using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed tracking event timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Tracking event timeline Reference","text","SPG03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("service-commitment-calculation","SPG04","Service commitment calculation","Execute service commitment calculation using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed service commitment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Service commitment calculation Reference","text","SPG04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("delivery-timestamp-validation","SPG05","Delivery timestamp validation","Execute delivery timestamp validation using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed delivery timestamp validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Delivery timestamp validation Reference","text","SPG05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("late-delivery-detection","SPG06","Late delivery detection","Execute late delivery detection using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed late delivery detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Late delivery detection Reference","text","SPG06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("exception-code-validation","SPG07","Exception code validation","Execute exception code validation using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed exception code validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Exception code validation Reference","text","SPG07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("weather-waiver-review","SPG08","Weather waiver review","Execute weather waiver review using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed weather waiver review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Weather waiver review Reference","text","SPG08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("peak-waiver-control","SPG09","Peak waiver control","Execute peak waiver control using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed peak waiver control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Peak waiver control Reference","text","SPG09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("address-correction-audit","SPG10","Address correction audit","Execute address correction audit using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed address correction audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Address correction audit Reference","text","SPG10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("refund-eligibility-calculation","SPG11","Refund eligibility calculation","Execute refund eligibility calculation using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed refund eligibility calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Refund eligibility calculation Reference","text","SPG11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("carrier-refund-submission","SPG12","Carrier refund submission","Execute carrier refund submission using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed carrier refund submission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Carrier refund submission Reference","text","SPG12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("denial-appeal-workflow","SPG13","Denial appeal workflow","Execute denial appeal workflow using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed denial appeal workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Denial appeal workflow Reference","text","SPG13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("credit-invoice-reconciliation","SPG14","Credit invoice reconciliation","Execute credit invoice reconciliation using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed credit invoice reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Credit invoice reconciliation Reference","text","SPG14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]}),
feature("carrier-service-analytics","SPG15","Carrier service analytics","Execute carrier service analytics using carrier agreements, manifests, tracking scans, service commitments, delivery timestamps, exceptions, weather events, invoices, refund requests, and credits.","Produce a governed carrier service analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Package Population","text","Carrier / Package Population · Standard Case"],["caseReference","Carrier service analytics Reference","text","SPG15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1236250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1495863],["domainDriver","Failure Type","select","Late delivery",["Late delivery","Saturday failure","Address correction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Carrier agreement library case","Package manifest ingestion case","Tracking event timeline case","Service commitment calculation case","Delivery timestamp validation case"]})
]);
